### ISSUE TITLE
초대하기 기능 재정의

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-back#103]
상대방이 동의하지 않았는데, 방에 초대가 될 수 있습니다.

_Originally posted by @14KGun in https://github.com/sparcs-kaist/taxi-back/pull/102#discussion_r942760581_

방 초대하기에 대하여 기능과 api 재정의가 필요할 것 같습니다.

**Comment by withSang** [comment]
현재로서는 /rooms/invite API가 공개된 방을 요청을 보낸 사용자가 직접 참여할 때에만 사용될 예정이니, /rooms/join으로 API 이름을 바꾸고 방에 다른 사람을 초대하는 기능을 삭제하는 것도 방법일 것 같습니다.
