### ISSUE TITLE
nickname 공백 3개 입력 불가능하게 하기

### ISSUE THREAD

**Issue by Hyogyeong8** [sparcs-kaist/taxi-back#136]
# Summary 

nickname에 공백 3개를 입력해도 수정 가능합니다. -> 공백을 제한합니다. 

# Tasks 

- [ ] 공백이 연달아 있을 때 모두 공백 하나로 줄여버리는 정규식 작성
- [ ] front에도 반영

**Comment by 14KGun** [comment]
Tasks 채워주세요 !!
그리고 Label, Project 선택하셔야합니다.
@Hyogyeong8

**Comment by Hyogyeong8** [comment]
> Tasks 채워주세요 !! 그리고 Label, Project 선택하셔야합니다. @Hyogyeong8

front에서 막아야 할 것 같다는 생각도 들어서 issue를 삭제하고 새로 만들어도 될 것 같아요
