### ISSUE TITLE
SSO로그인에서 카이스트 구성원 검증

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-back#147]
# Summary 

스팍스SSO로 로그인하였을 때, 카이스트 구성원 검증을 추가합니다.
(학사,석사,박사,교수님만 로그인이 가능하도록 설정합니다)
(포탈 로그인 외, sso 아이디 로그인, 소셜 로그인을 막기 위함입니다)
(prod모드로 빌드하였을 경우만 검증을 하여야 합니다)

**Comment by withSang** [comment]
https://wiki.sparcs.org/index.php/SPARCS_SSO/KAIST_SSO_%EB%AA%85%EC%84%B8
kaistInfo가 존재하는지 한 번 확인하고, 1) ku_acad_prod_code(학부생/대학원생/청강생에게만 존재하는 속성)가 존재하는지 확인하거나, 2) employeeType이 "S"이거나 "ES"이거나 "P"인지 검사하면 될 것 같아요.
테스트하는 데 시간이 좀 걸리고 만드는 건 금방 될 것 같아요.

**Comment by withSang** [comment]
앗 교수님 로그인 허용하려면 두번째 방법이 낫겠어요. 커밋 올려보겠습니당

**Comment by withSang** [comment]
앗 교수님들 서비스 이용을 허용하려면 두번째 방법이 맞겠어요!

**Comment by 14KGun** [comment]
> 앗 교수님들 서비스 이용을 허용하려면 두번째 방법이 맞겠어요!

좋은 것 같습니다 ~~~
