### ISSUE TITLE
[Bug] admin 페이지 rate-limit 제외

### ISSUE THREAD

**Issue by Hyogyeong8** [sparcs-kaist/taxi-back#153]
# Describe the bug
admin의 경우 crawling을 막기 위한 rate-limit에 걸려 에러가 발생한다. 
rate limit이 낮아서 페이지 이동 시 rate-limit에 쉽게 걸린다.

**Comment by GrasshopperBears** [comment]
1. dev 환경에서는 rate limit 안걸리게 해주시면 좋을 것 같아요!
2. `/json/logininfo`도 제외 목록에 추가해주시면 감사하겠습니다. 혹은 특정 API만 limit 상한선을 설정할 수 있다면 높여주시면 좋을 것 같아요.
페이지를 이동할 때마다 이 API도 호출하는데 100번은 조금 낮을 수도 있을 것 같아요. 테스트하다가 금방 limit에 걸려버렸습니다...

**Comment by 14KGun** [comment]
> 1. dev 환경에서는 rate limit 안걸리게 해주시면 좋을 것 같아요!
> 2. `/json/logininfo`도 제외 목록에 추가해주시면 감사하겠습니다. 혹은 특정 API만 limit 상한선을 설정할 수 있다면 높여주시면 좋을 것 같아요.
>    페이지를 이동할 때마다 이 API도 호출하는데 100번은 조금 낮을 수도 있을 것 같아요. 테스트하다가 금방 limit에 걸려버렸습니다...

저도 개발 테스트 중에 rate-limit 걸려서 back 껏다킵니다. rate-limit이 너무 낮게 설정되어 있는 것 같아요.
