### ISSUE TITLE
[Bug] 방이 비워있는 경우, 방 자동 삭제

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-back#157]
# Describe the bug
탑승 취소로 인해 방에 남아있는 인원이 없는 경우, 방을 자동으로 삭제합니다.

**Comment by withSang** [comment]
공동코딩 하면서 얘기가 나왔는데 방에 대한 신고가 들어온 뒤 모든 사용자가 방을 나가면 해당 방이 DB에 남아있지 않아 신고 처리가 불가능하지 않을까 걱정돼요!

**Comment by 14KGun** [comment]
> 공동코딩 하면서 얘기가 나왔는데 방에 대한 신고가 들어온 뒤 모든 사용자가 방을 나가면 해당 방이 DB에 남아있지 않아 신고 처리가 불가능하지 않을까 걱정돼요!

@withSang 그러면 DB에서 지우지는 말고, 검색 페이지에서 방이 검색되지 않도록 하는 것 어떤가요??
@Hyogyeong8

**Comment by withSang** [comment]
> > 공동코딩 하면서 얘기가 나왔는데 방에 대한 신고가 들어온 뒤 모든 사용자가 방을 나가면 해당 방이 DB에 남아있지 않아 신고 처리가 불가능하지 않을까 걱정돼요!
> 
> @withSang 그러면 DB에서 지우지는 말고, 검색 페이지에서 방이 검색되지 않도록 하는 것 어떤가요??
> @Hyogyeong8 

우와 좋은 것 같아요!! 지난번에 효경님께서도 그런 말씀 하셨어요

**Comment by Hyogyeong8** [comment]
> DB에서 지우지는 말고, 검색 페이지에서 방이 검색되지 않도록 하는 것 어떤가요??

넵 그럼 그렇게 수정하겠습니다!
