### ISSUE TITLE
[Bug] 졸업생 로그인 불가

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-back#178]
# Describe the bug
졸업생 로그인 불가

**Comment by withSang** [comment]
<img width="484" alt="image" src="https://user-images.githubusercontent.com/46402016/201041390-5e16cf03-6c4f-4543-965b-9cbd5462db2e.png">
`"^[PEU][SA]|[PEU]|[SA]$"`면 되겠어요!

**Comment by withSang** [comment]
오 `"^[PEUR][SA]|[PEUR]|[SA]$"`가 아니라 `"^([PEUR][SA]|[PEUR]|[SA])$"`요!
