### ISSUE TITLE
locations schema에 정렬 기준 추가

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-back#183]
# Summary 

mongo DB locations schema에 정렬 기준을 추가합니다.
또한 "/locations" API에서 정렬된 locations를 반환하도록 수정합니다.

# Tasks 

- [ ] mongo DB locations schema에 정렬 기준을 추가
- [ ] "/locations" API에서 정렬된 locations를 반환하도록 수정

**Comment by imYourChoi** [comment]
제일 위에 택시 승강장과 대전역이 오고 나머지 옵션들은 가나다 순으로 정렬되게 할수 있나요~

**Comment by 14KGun** [comment]
> 제일 위에 택시 승강장과 대전역이 오고 나머지 옵션들은 가나다 순으로 정렬되게 할수 있나요~

가능합니다만, 논의 한번 거쳐야 할 것 같긴 하네요
