### ISSUE TITLE
taxiSampleGanerator 이전

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-back#184]
# Summary 

[taxiSampleGenerator](https://github.com/sparcs-kaist/taxiSampleGenerator) 를 taxi-back repo로 이전합니다.
`npm test`의 명령어 사용과 github action ci를 mondodb dump 파일이 아닌 `taxiSampleGenerator` 실행 후 시행되도록 `package.json`을 수정합니다.

# Tasks 

- [x] `taxiSampleGenerator` 이전
- [ ] `package.json` 수정

_Originally posted by @14KGun in https://github.com/sparcs-kaist/taxi-back/issues/174#issuecomment-1308082904_

**Comment by 14KGun** [comment]
@withSang 이거 제가 이전 작업 해도 되나요??

**Comment by withSang** [comment]
헉 넵 그런데 코드가 썩 깔끔하지는 않아요 ㅠ.ㅠ

**Comment by 14KGun** [comment]
@chlehdwon @withSang `taxiSamplegenerator`를 git submodule로 가져오도록 작업해주시면 될 것 같습니다 ~

**Comment by chlehdwon** [comment]
> @chlehdwon @withSang `taxiSamplegenerator`를 git submodule로 가져오도록 작업해주시면 될 것 같습니다 ~

앗 어제 taxi-back안에 taxiSampleGenerator가 위치하도록 만들었는데 git submodule로 바꿀까요...?

**Comment by chlehdwon** [comment]
@14KGun
github action에서 taxiSampleGenerator를 실행시키려면 security 정보에 방 개수나 입력 시간 같은 parameter들을 다 넣어줘야 하더라고요... 그래서 @withSang 님과 얘기해서 taxiSampleGenerator에 issue 팠으니 한 번 확인해주세요!
