### ISSUE TITLE
로그인 만료 시간이 너무 짧음

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-back#188]
# Summary 

로그인 만료 기간이 1시간으로 짧은 감이 있습니다. 하루 정도로 늘리는게 좋을 것 같습니다.

# Tasks 

- [x] 로그인 세션의 만료 기한을 1주로 연장합니다.

**Comment by 14KGun** [comment]
2022-11-22 회의 논의로 세션 만료 기한을 2주로 연장하기로 결정하였습니다
