### ISSUE TITLE
앱 토큰 생성 과정 중 에러

### ISSUE THREAD

**Issue by happycastle114** [sparcs-kaist/taxi-back#222]
# Summary 

local 에서는 에러 발생 X

taxi.sparcs.org 서버에서 /api/auth/app/token/generate 로 접근 시 Nginx 502 에러 발생

# Tasks

**Comment by withSang** [comment]
https://github.com/sparcs-kaist/taxi-docker/issues/20
제보 감사합니다! 말씀해주신 대로 원인 찾아 해결했습니다.
