### ISSUE TITLE
Directory Structure Refactoring

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-back#229]
# Summary 

아래와 같은 구조로 전체 디렉토리 이름을 수정하고 코드 파일들을 이동시킵니다.

```plain
├ src
│ ├ middlewares (→ 디렉토리명 수정)
│ │ └ ...
│ ├ modules
│ │ ├ stores
│ │ │ ├ awsS3.js (→ 파일 이동)
│ │ │ └ mongo.js (→ 파일 이동)
│ │ ├ auths
│ │ │ ├ login.js (→ 파일 이동)
│ │ │ ├ sparcssso.js (→ 파일 이동)
│ │ │ └ jwt.js (→ 파일 이동)
│ │ ├ populates (→ 추후 모든 populates 함수들 이 디렉토리로 이동시키는 것은 어떠할지?)
│ │ │ └ rooms.js (→ 파일 이동)
│ │ ├ patterns.js (→ 파일 이동, 나중에 validator 미들웨어로 감싼다음 middlewares 디렉토리로 이동시키는 것은 어떠할지?)
│ │ ├ logAPIAccess.js
│ │ ├ logger.js
│ │ ├ modifyProfile.js
│ │ └ socket.js
│ ├ routes (→ 디렉토리명 수정)
│ │ ├ docs 
│ │ │ └ ...
│ │ └ ...
│ └ services (→ 디렉토리명 수정)
│   ├ chats.socket.js (→ route에서 services로 파일 이동)
│   └ ...
├ test
│ └ ...
├ app.js
├ loadenv.js (→ 파일명 수정 및 config/constants.js와 config/secretKey.js 기능 이동)
└ ...
```

**Comment by 14KGun** [comment]
@withSang @ptptsw @chlehdwon @happycastle114 이런식으로 전체 구조 변경하는 거 어떠신가요?

**Comment by chlehdwon** [comment]
`src `내부 파일 구조가 더 깔끔해지고, 단/복수 명칭이 통일되는 것 같아서 저는 아주 마음에 들어요👍 
`patterns.js`도 validation을 위한 것이니 `middlewares`로 보내는 게 더 좋을 것 같구요!
그러면 이제 `loadenv.js`에서 `security.js`와 `config` 디렉토리의 역할을 다 해준다고 보면 되나요?

**Comment by 14KGun** [comment]
> `src` 내부 파일 구조가 더 깔끔해지고, 단/복수 명칭이 통일되는 것 같아서 저는 아주 마음에 들어요👍 `patterns.js`도 validation을 위한 것이니 `middlewares`로 보내는 게 더 좋을 것 같구요! 그러면 이제 `loadenv.js`에서 `security.js`와 `config` 디렉토리의 역할을 다 해준다고 보면 되나요?

@chlehdwon 네네, 의도대로라면 그렇습니다!! 두 파일이 config 값들 불러오는 역할을 하는데 역할 중복이 된다는 판단하에 합쳤습니다.

**Comment by chlehdwon** [comment]
> > `src` 내부 파일 구조가 더 깔끔해지고, 단/복수 명칭이 통일되는 것 같아서 저는 아주 마음에 들어요👍 `patterns.js`도 validation을 위한 것이니 `middlewares`로 보내는 게 더 좋을 것 같구요! 그러면 이제 `loadenv.js`에서 `security.js`와 `config` 디렉토리의 역할을 다 해준다고 보면 되나요?
> 
> @chlehdwon 네네, 의도대로라면 그렇습니다!! 두 파일이 config 값들 불러오는 역할을 하는데 역할 중복이 된다는 판단하에 합쳤습니다.

@14KGun 아하 알겠습니댜! 저는 이대로 가도 좋을 것 같아요

**Comment by withSang** [comment]
좋아보임돠 ㅎㅎ 문서화하기 편해보여요
