### ISSUE TITLE
방 이름 정규식에서 '~'를 비롯한 특수문자 허용

### ISSUE THREAD

**Issue by Hyogyeong8** [sparcs-kaist/taxi-back#265]
# Summary 

방 이름 정규식에서 '~'를 비롯한 특수문자를 허용합니다.

**Comment by 14KGun** [comment]
이 이슈에서 계좌번호 정규식도 `"^[A-Za-z가-힣]{2,7} [0-9]{10,14}$"` 에서 `"^[A-Za-z가-힣]{2,7} ([0-9]{10,14}|)$"`으로 수정합니다
