### ISSUE TITLE
신고 대응 이메일 전송 페이지 제작

### ISSUE THREAD

**Issue by Hyogyeong8** [sparcs-kaist/taxi-back#310]
# Summary 

신고에 대응하는 이메일 전송을 자동화하기 위해 필요한 페이지를 제작합니다. 

아래 이미지의 템플릿을 따릅니다.

![미정산 안내](https://github.com/sparcs-kaist/taxi-back/assets/69258815/e11837ed-1861-4ded-8401-b1e825d0000e)

# Tasks 

- [ ] 미리보기 페이지
- [ ] 보내시겠습니까 확인하는 모달 등 이외에 필요한 페이지
- [ ] 이메일 로직 논의

**Comment by 14KGun** [comment]
@withSang 
`template` 관련해서는 구지 AWS 에서 관리하지 않고,
`taxi-back`에서 본문 입력한 다음 완성된 HTML 파일 쏴주면 되지 않을까요??

**Comment by withSang** [comment]
> @withSang 
> `template` 관련해서는 구지 AWS 에서 관리하지 않고,
> `taxi-back`에서 본문 입력한 다음 완성된 HTML 파일 쏴주면 되지 않을까요??

오 좋아요!!
