### ISSUE TITLE
이벤트 참여 동의 여부 확인

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-back#372]
# Summary

이벤트 참여 동의를 받는 API 를 제작합니다. 그리고 이벤트 참여 미동의자는 퀘스트 완료 가 불가능 하도록 막습니다.

> 음.. 나중에 이벤트 참여 동의 여부도 `eventStatusSchema`에 포함되어 할 것 같습니다.
> 그리고 동의 하지 않은 사용자들 퀘스트 달성이랑 아이템 구입 막아야 할듯요...
>
> 이건 다른 PR에서 하면 좋을 것 같아요

_Originally posted by @14KGun in https://github.com/sparcs-kaist/taxi-back/pull/364#discussion_r1328053193_

**Comment by kmc7468** [comment]
현재는 global-state 호출되었을 때, completeQuest 함수 호출되었을 때 EventStatus 생성이 일어납니다.

이벤트 참여 동의를 받은 후에만 EventStatus가 생성되도록 하고, 동시에 firstLoginQuest가 달성되도록 구현할 필요가 있습니다.

**Comment by 14KGun** [comment]
> 현재는 global-state 호출되었을 때, completeQuest 함수 호출되었을 때 EventStatus 생성이 일어납니다.
> 
> 이벤트 참여 동의를 받은 후에만 EventStatus가 생성되도록 하고, 동시에 firstLoginQuest가 달성되도록 구현할 필요가 있습니다.

@kmc7468 오 좋은 것 같습니다
