### ISSUE TITLE
이벤트 참여 동의 받을 때 전화번호 수집

### ISSUE THREAD

**Issue by kmc7468** [sparcs-kaist/taxi-back#377]
# Summary 

`/events/2023fall/global-state/create` API에서 전화번호를 함께 받도록 구현해야 합니다.
정규식을 활용하여 유효한 전화번호인지 확인해야 합니다.
수집한 전화번호는 User Schema에 저장합니다.

# Tasks 

- [ ] 스키마 수정
- [ ] `create` API 수정

**Comment by cokia** [comment]
@cokia 제가 금일중으로 처리하겠습니다 :D
