### ISSUE TITLE
Simplify rooms API

### ISSUE THREAD

**Issue by withSang** [sparcs-kaist/taxi-back#39]
- url의 일관성을 위해 방 정보 조회 API를 바꿀 수 있습니다. → **rooms/:id/info API를 사용하는 프론트 쪽 컴포넌트들 모두 수정 필요**
`"/:id/info"` → `"/info/:id"`  또는 `"/info?id="`
- `"/rooms/create"` API의 경우, Request body를 아래와 같이 더 직관적으로 정의할 수 있습니다.
`{data: {name: “~~”, from: “~~”, to: “~~”}, ...}` → `{name: “~~”,  from: “~~”, to: “~~”, ...}`

**Comment by hyeongjunCho** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2022-04-25T16:41:09
          
          
            * 메일 제목 : 
[sparcs-kaist/taxi-back] Simplify rooms API (Issue #39)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
