### ISSUE TITLE
Modify  Done Room 

### ISSUE THREAD

**Issue by ptptsw** [sparcs-kaist/taxi-back#45]
- 현재 과거 방은 날짜 기준으로, 현재 시간 기준으로 과거면 과거방으로 나옵니다.
- 이 기준을 시간이 아닌 정산완료 여부로 변경해, 모든 맴버들이 정산이 완료되었을 때  과거방이 되도록 변경하려고 합니다.

**Comment by withSang** [comment]
@ptptsw 님께서 작업 끝내신 내용이라 닫으셔도 될 것 같아요! @14KGun
이슈: https://github.com/sparcs-kaist/taxi-back/issues/50
PR: https://github.com/sparcs-kaist/taxi-back/pull/51
